name: CI test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test container rabbitmq
      run: |
        docker run --network container:container-rabbitmq-queue jwilder/dockerize -wait http://localhost:15672 -timeout 120s -wait-retry-interval 5s

    - name: Test container micro-live-manager-backend
      run: |
        docker run --network container:micro-live-manager-backend jwilder/dockerize -wait http://localhost:3333/api/lives -timeout 300s -wait-retry-interval 5s

    - name: Test container micro-live-manager-frontend
      run: |
        docker run --network container:micro-live-manager-frontend jwilder/dockerize -wait http://localhost:8000 -timeout 120s -wait-retry-interval 5s
    
    - name: Test container micro-live-streaming
      run: |
        docker run --network container:micro-live-streaming jwilder/dockerize -wait http://localhost:4000 -timeout 120s -wait-retry-interval 5s
  